name: Release to Test Pipeline

on:
  push:
    branches:
      - release

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

  deploy_to_test:
    needs: integration_tests
    runs-on: ubuntu-latest
    if: ${{ needs.integration_tests.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push release branch into test_repo
        uses: codingforentrepreneurs/action-branch-to-branch@main
        with:
          dest_branch: 'test_repo'
          source_branch: 'release'
          commit_message: 'Release production version'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

          #test

