name: PR create

on:
  push:
    branches:
      - main


jobs:
  databricks_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyGithub
          pip install pytest bandit


      - name: List installed packages
        run: pip list

      - name: Create Pull Request
        run: python .github/workflows/create_pull_request.py ${{ secrets.PAT_TOKEN }}
