name: Databricks job migration

on:
  workflow_dispatch:
    inputs:
      source_env:
        description: "Select source environment"
        required: true
        options: ["Dev", "Test", "Prod"]

jobs:
  databricks_migration:
    runs-on: ubuntu-latest

    env:
      SOURCE_ENV: ${{ github.event.inputs.source_env }}
      TARGET_ENV: test
      DATABRICKS_API_TOKEN: ${{ secrets.DATABRICKS_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests
  
      - name: Call Databricks API
        run: |
          python .github/workflows/apicall.py

