
# name: SecondWorkflow


# on:
#   workflow_run:
#     workflows: ["Databricks job migration"]
#     types: [completed]
#     branches:
#       - 'dev_jobs/**'
      
  # workflow_dispatch:
  #   inputs:
  #     job_ids:
  #       description: "Select job IDs (comma-separated)"
  #       required: true
  #       type: choice

name: Select and Run Job

on:
  workflow_run:
    workflows: ["Databricks job migration"]
    types:
      - completed

jobs:
  select_and_run_job:
    runs-on: ubuntu-latest

    steps:
      - name: Download Job IDs Artifact
        uses: actions/download-artifact@v2
        with:
          name: job-ids

      - name: Gather User Input
        id: user_input
        run: |
          job_ids=$(cat job-ids)
          echo "Available Job IDs: $job_ids"
          echo "Please enter the Job ID you want to use:"
          read selected_job_id
          echo "::set-output name=selected_job_id::${selected_job_id}"
        shell: bash

      - name: Set up Git
        run: |
          git config --global user.name "monika"
          git config --global user.email "monika.sakare@capgemini.com"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Commit Selected Job ID
        run: |
          selected_job_id="${{ steps.user_input.outputs.selected_job_id }}"
          echo "Selected Job ID: $selected_job_id" > selected_job_id.txt
          git add selected_job_id.txt
          git commit -m "Add selected Job ID"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      # - name: Get Job IDs Input
      #   id: get_job_ids
      #   run: echo "::set-output name=job_ids::${{ github.event.inputs.job_ids }}"
      #   shell: bash
      #   env:
      #     job_ids: ${{ github.event.inputs.job_ids }}

      # - name: Display Selected Job IDs
      #   run: |
      #     selected_job_ids="${{ steps.get_job_ids.outputs.job_ids }}"
      #     echo "Selected Job IDs: $selected_job_ids"
