name: PR Comment Listener

on:
  issue_comment:
    types:
      - created

jobs:
  process_pr_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the comment is on a PR
        run: echo "Comment body: ${{ github.event.comment.body }}"
        
      - name: Check if the comment contains a job ID
        run: |
          # Use regular expressions or other methods to extract the job ID from the comment body
          # Example: Extracting job ID like "[Job ID: 12345]"
          job_id=$(echo "${{ github.event.comment.body }}" | grep -oP '\[Job ID: \K\d+(?=\])')
          echo "::set-output name=job_id::$job_id"
          
      - name: Trigger Main Workflow with Job ID
        if: steps.process_pr_comment.outputs.job_id != ''
        run: |
          # Extracted job ID from the comment
          job_id="${{ steps.process_pr_comment.outputs.job_id }}"
          
          # Trigger the main workflow with the selected job ID as an input
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main_workflow.yml/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"selected_job_id\":\"$job_id\"}}"
